export const constants = Object.freeze({
  minZoom: 0.35,
  maxZoom: 40000,
  panSpeed: 1,
  panLimit: 100000,
  nodeDoubleClickWindow: 450,
  nodeDoubleClickDistance: 12,
  windowedFitZoom: 1.45,
  expandedFitZoom: 1
});

function embeddedLayoutProfile(exportData) {
  const profile = exportData && exportData.layout_profile ? exportData.layout_profile : {};
  return {
    algorithm: profile.algorithm || "layered",
    options: Object.assign({}, profile.options || {})
  };
}

export function createContext() {
  const modelID = document.querySelector('meta[name="model-id"]').content;
  const analysisRunID = document.querySelector('meta[name="analysis-run-id"]').content;
  const aggregateEnabled = document.querySelector('meta[name="aggregate-enabled"]').content === "true";
  const embeddedExport = window.__ARCH_VIEW_EXPORT__ || null;
  const sourceEnabled = document.querySelector('meta[name="source-enabled"]').content === "true";
  const reanalysisEnabled = document.querySelector('meta[name="reanalysis-enabled"]').content === "true";
  const workerURL = document.querySelector('meta[name="worker-url"]').content;
  const state = {
    model: null,
    scopes: [],
    activeScope: aggregateEnabled ? "all" : "",
    scopeRequest: 0,
    scene: null,
    selected: null,
    sourceIndex: null,
    sourceIndexError: "",
    sourceIndexRequest: 0,
    query: "",
    referenceVisibility: "hidden",
    importScope: "all",
    layout: null,
    layoutProfile: embeddedLayoutProfile(embeddedExport),
    layoutCatalog: embeddedExport && embeddedExport.layout_catalog ? embeddedExport.layout_catalog : null,
    layoutConfig: null,
    layoutDraft: null,
    layoutOptionSearch: "",
    layoutMessage: "",
    layoutMessageError: false,
    layoutSettingsOpen: false,
    layoutConfigRequest: 0,
    layoutKey: "",
    layoutRequest: 0,
    layoutError: false,
    viewport: null,
    draggingNode: null,
    dragFrame: 0,
    history: [],
    scrollContexts: {},
    sceneRequest: 0,
    source: null,
    sourceRequest: 0,
    viewMode: "graph",
    inspectionSection: "overview",
    inspectionRoute: null,
    inspectionFilters: { files: "", symbols: "" },
    inspectionSymbolKind: "",
    inspectionSymbolKinds: [],
    inspectionDocumentation: {},
    inspectionDocumentationRequested: {},
    inspectionCache: {},
    inspectionRequest: 0,
    inspectionSnapshot: null,
    qualityReport: null,
    qualityReportEnvelope: null,
    qualityReportStatus: "loading",
    qualityReportError: "",
    qualityReportCache: {},
    qualityReportRequest: 0,
    qualityProfiles: [],
    qualityProfilesStatus: "loading",
    qualityProfilesError: "",
    qualityProfilesRequest: 0,
    activeQualityProfile: null,
    activeQualityProfileKey: "",
    qualityEvaluationStatus: "idle",
    qualityEvaluationTemporary: false,
    qualityEvaluationError: "",
    qualityEvaluationRequest: 0,
    qualityRuleCatalog: [],
    qualityRuleCatalogStatus: "idle",
    qualityRuleCatalogError: "",
    qualityRuleCatalogRequest: 0,
    qualityRuleDraft: null,
    qualityRuleDialogOriginal: null,
    qualityRuleSearch: "",
    qualityProfileSaveStatus: "idle",
    qualityProfileSaveError: "",
    qualityProfileSaveAsOpen: false,
    qualityBaselineStatus: "idle",
    qualityBaselineError: "",
    qualityBaselineMessage: "",
    qualityBaselineDialogOpen: false,
    qualityBaselineAllActive: true,
    qualityBaselineSelectedFindings: [],
    qualityFindingsPage: null,
    qualityFindingsCache: {},
    qualityFindingsLoading: false,
    qualityFindingsError: "",
    qualityFindingRuleFilter: "",
    qualityEvidence: null,
    qualityAffectedOnly: false,
    suppressClickUntil: 0,
    lastNodeClick: null,
    nativeFullscreen: false,
    aggregateError: "",
    scopePickerBound: false
  };
  const elements = {
    projectLabel: document.getElementById("project-label"),
    modelStatus: document.getElementById("model-status"),
    viewDescription: document.getElementById("view-description"),
    summary: document.getElementById("summary"),
    errorBanner: document.getElementById("error-banner"),
    graphView: document.getElementById("graph-view"),
    inspectionView: document.getElementById("inspection-view"),
    sceneState: document.getElementById("scene-state"),
    layerLegend: document.getElementById("layer-legend"),
    referenceSummary: document.getElementById("reference-summary"),
    graph: document.getElementById("graph-wrap"),
    detailsTitle: document.getElementById("details-title"),
    detailsKind: document.getElementById("details-kind"),
    detailsContext: document.getElementById("details-context"),
    detailsContent: document.getElementById("details-content"),
    accessibleList: document.getElementById("accessible-list"),
    listCount: document.getElementById("list-count"),
    listToggle: document.getElementById("list-toggle"),
    inspectionBack: document.getElementById("inspection-back"),
    inspectionTitle: document.getElementById("inspection-title"),
    inspectionSubtitle: document.getElementById("inspection-subtitle"),
    inspectionScope: document.getElementById("inspection-scope"),
    inspectionScopeStatus: document.getElementById("inspection-scope-status"),
    inspectionNavigation: document.getElementById("inspection-navigation"),
    inspectionContent: document.getElementById("inspection-content"),
    cycles: document.getElementById("cycles"),
    cycleCount: document.getElementById("cycle-count"),
    diagnostics: document.getElementById("diagnostics"),
    diagnosticCount: document.getElementById("diagnostic-count"),
    footerModelID: document.getElementById("footer-model-id"),
    search: document.getElementById("search"),
    referenceVisibility: document.getElementById("reference-visibility"),
    scopeSelectorControl: document.getElementById("scope-selector-control"),
    scopeSelector: document.getElementById("scope-selector"),
    scopeSelectorButton: document.getElementById("scope-selector-button"),
    scopeSelectorMenu: document.getElementById("scope-selector-menu"),
    qualityProfileControl: document.getElementById("quality-profile-control"),
    qualityProfile: document.getElementById("quality-profile"),
    qualityProfileStatus: document.getElementById("quality-profile-status"),
    qualityProfileConfigure: document.getElementById("quality-profile-configure"),
    qualityProfileDialog: document.getElementById("quality-profile-dialog"),
    qualityProfileClose: document.getElementById("quality-profile-close"),
    qualityProfileCancel: document.getElementById("quality-profile-cancel"),
    qualityProfileApply: document.getElementById("quality-profile-apply"),
    qualityProfileSave: document.getElementById("quality-profile-save"),
    qualityProfileSaveAs: document.getElementById("quality-profile-save-as"),
    qualityProfileSaveAsPanel: document.getElementById("quality-profile-save-as-panel"),
    qualityProfileSaveAsFile: document.getElementById("quality-profile-save-as-file"),
    qualityProfileSaveAsID: document.getElementById("quality-profile-save-as-id"),
    qualityProfileSaveAsVersion: document.getElementById("quality-profile-save-as-version"),
    qualityProfileSaveAsConfirm: document.getElementById("quality-profile-save-as-confirm"),
    qualityProfileSaveAsCancel: document.getElementById("quality-profile-save-as-cancel"),
    qualityProfileSaveAsSubmit: document.getElementById("quality-profile-save-as-submit"),
    qualityBaselineDialog: document.getElementById("quality-baseline-dialog"),
    qualityBaselineClose: document.getElementById("quality-baseline-close"),
    qualityBaselineCancel: document.getElementById("quality-baseline-cancel"),
    qualityBaselineSubmit: document.getElementById("quality-baseline-submit"),
    qualityBaselineAllActive: document.getElementById("quality-baseline-all-active"),
    qualityBaselineFindingSelection: document.getElementById("quality-baseline-finding-selection"),
    qualityBaselineFile: document.getElementById("quality-baseline-file"),
    qualityBaselineID: document.getElementById("quality-baseline-id"),
    qualityBaselineRevision: document.getElementById("quality-baseline-revision"),
    qualityBaselineReason: document.getElementById("quality-baseline-reason"),
    qualityBaselineOwner: document.getElementById("quality-baseline-owner"),
    qualityBaselineAttach: document.getElementById("quality-baseline-attach"),
    qualityBaselineStatus: document.getElementById("quality-baseline-status"),
    qualityRuleSearch: document.getElementById("quality-rule-search"),
    qualityRuleSummary: document.getElementById("quality-rule-summary"),
    qualityRuleCatalog: document.getElementById("quality-rule-catalog"),
    qualityProfileEditorStatus: document.getElementById("quality-profile-editor-status"),
    reanalysisButton: document.getElementById("reanalysis-button"),
    backButton: document.getElementById("back-button"),
    breadcrumbs: document.getElementById("breadcrumbs"),
    focusToggle: document.getElementById("focus-toggle"),
    downloadSVG: document.getElementById("download-svg"),
    zoomOut: document.getElementById("zoom-out"),
    zoomIn: document.getElementById("zoom-in"),
    zoomValue: document.getElementById("zoom-value"),
    resetZoom: document.getElementById("reset-zoom"),
    fitViewport: document.getElementById("fit-viewport"),
    resetLayout: document.getElementById("reset-layout"),
    layoutSettingsButton: document.getElementById("layout-settings-button"),
    layoutSettingsDialog: document.getElementById("layout-settings-dialog"),
    layoutSettingsClose: document.getElementById("layout-settings-close"),
    layoutSettingsOrigin: document.getElementById("layout-settings-origin"),
    layoutSettingsDiagnostic: document.getElementById("layout-settings-diagnostic"),
    layoutAlgorithm: document.getElementById("layout-algorithm"),
    layoutAlgorithmHelp: document.getElementById("layout-algorithm-help"),
    layoutOptionSearch: document.getElementById("layout-option-search"),
    layoutOptionsList: document.getElementById("layout-options-list"),
    layoutSaveAsDirectory: document.getElementById("layout-save-as-directory"),
    layoutSaveAsConfirm: document.getElementById("layout-save-as-confirm"),
    layoutSettingsStatus: document.getElementById("layout-settings-status"),
    layoutResetDefaults: document.getElementById("layout-reset-defaults"),
    layoutSettingsApply: document.getElementById("layout-settings-apply"),
    layoutSettingsSave: document.getElementById("layout-settings-save"),
    layoutSettingsSaveAs: document.getElementById("layout-settings-save-as")
  };
  return { modelID, analysisRunID, aggregateEnabled, embeddedExport, sourceEnabled, reanalysisEnabled, workerURL, state, elements, constants };
}
