export const constants = Object.freeze({
  minZoom: 0.35,
  maxZoom: 40000,
  panSpeed: 1,
  panLimit: 100000,
  nodeDoubleClickWindow: 450,
  nodeDoubleClickDistance: 12,
  windowedFitZoom: 1.45,
  expandedFitZoom: 1
});

export function createContext() {
  const modelID = document.querySelector('meta[name="model-id"]').content;
  const embeddedExport = window.__ARCH_VIEW_EXPORT__ || null;
  const sourceEnabled = document.querySelector('meta[name="source-enabled"]').content === "true";
  const reanalysisEnabled = document.querySelector('meta[name="reanalysis-enabled"]').content === "true";
  const workerURL = document.querySelector('meta[name="worker-url"]').content;
  const state = {
    model: null,
    scene: null,
    selected: null,
    query: "",
    referenceVisibility: "hidden",
    importScope: "all",
    layout: null,
    layoutProfile: { algorithm: "layered", options: {} },
    layoutCatalog: null,
    layoutConfig: null,
    layoutDraft: null,
    layoutOptionSearch: "",
    layoutMessage: "",
    layoutMessageError: false,
    layoutSettingsOpen: false,
    layoutConfigRequest: 0,
    layoutKey: "",
    layoutRequest: 0,
    layoutError: false,
    viewport: null,
    draggingNode: null,
    dragFrame: 0,
    history: [],
    scrollContexts: {},
    sceneRequest: 0,
    source: null,
    sourceRequest: 0,
    suppressClickUntil: 0,
    lastNodeClick: null,
    nativeFullscreen: false
  };
  const elements = {
    projectLabel: document.getElementById("project-label"),
    modelStatus: document.getElementById("model-status"),
    viewDescription: document.getElementById("view-description"),
    summary: document.getElementById("summary"),
    errorBanner: document.getElementById("error-banner"),
    sceneState: document.getElementById("scene-state"),
    layerLegend: document.getElementById("layer-legend"),
    referenceSummary: document.getElementById("reference-summary"),
    graph: document.getElementById("graph-wrap"),
    detailsTitle: document.getElementById("details-title"),
    detailsKind: document.getElementById("details-kind"),
    detailsContent: document.getElementById("details-content"),
    accessibleList: document.getElementById("accessible-list"),
    listCount: document.getElementById("list-count"),
    listToggle: document.getElementById("list-toggle"),
    cycles: document.getElementById("cycles"),
    cycleCount: document.getElementById("cycle-count"),
    diagnostics: document.getElementById("diagnostics"),
    diagnosticCount: document.getElementById("diagnostic-count"),
    footerModelID: document.getElementById("footer-model-id"),
    search: document.getElementById("search"),
    referenceVisibility: document.getElementById("reference-visibility"),
    reanalysisButton: document.getElementById("reanalysis-button"),
    backButton: document.getElementById("back-button"),
    breadcrumbs: document.getElementById("breadcrumbs"),
    focusToggle: document.getElementById("focus-toggle"),
    zoomOut: document.getElementById("zoom-out"),
    zoomIn: document.getElementById("zoom-in"),
    zoomValue: document.getElementById("zoom-value"),
    resetZoom: document.getElementById("reset-zoom"),
    fitViewport: document.getElementById("fit-viewport"),
    resetLayout: document.getElementById("reset-layout"),
    layoutSettingsButton: document.getElementById("layout-settings-button"),
    layoutSettingsDialog: document.getElementById("layout-settings-dialog"),
    layoutSettingsClose: document.getElementById("layout-settings-close"),
    layoutSettingsOrigin: document.getElementById("layout-settings-origin"),
    layoutSettingsDiagnostic: document.getElementById("layout-settings-diagnostic"),
    layoutAlgorithm: document.getElementById("layout-algorithm"),
    layoutAlgorithmHelp: document.getElementById("layout-algorithm-help"),
    layoutOptionSearch: document.getElementById("layout-option-search"),
    layoutOptionsList: document.getElementById("layout-options-list"),
    layoutSaveAsDirectory: document.getElementById("layout-save-as-directory"),
    layoutSaveAsConfirm: document.getElementById("layout-save-as-confirm"),
    layoutSettingsStatus: document.getElementById("layout-settings-status"),
    layoutResetDefaults: document.getElementById("layout-reset-defaults"),
    layoutSettingsApply: document.getElementById("layout-settings-apply"),
    layoutSettingsSave: document.getElementById("layout-settings-save"),
    layoutSettingsSaveAs: document.getElementById("layout-settings-save-as")
  };
  return { modelID, embeddedExport, sourceEnabled, reanalysisEnabled, workerURL, state, elements, constants };
}
