package tsanalyzer

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"path"
	"path/filepath"
	"runtime"
	"sort"
	"strings"

	"github.com/buffo/arch-view/internal/analysis"
)

func safeProjectFile(root, relative string) bool {
	filePath := filepath.Join(root, filepath.FromSlash(relative))
	return existsAsFile(filePath) && safeFileWithinRoot(root, filePath)
}

func relativeProjectPath(root, filePath string) string {
	relative, err := filepath.Rel(filepath.Clean(root), filepath.Clean(filePath))
	if err != nil {
		return filepath.ToSlash(filepath.Clean(filePath))
	}
	if relative == "" {
		return "."
	}
	return filepath.ToSlash(filepath.Clean(relative))
}

func tsPathKey(value string) string {
	value = filepath.Clean(value)
	if runtime.GOOS == "windows" {
		return strings.ToLower(value)
	}
	return value
}

func pathWithin(root, candidate string) bool {
	relative, err := filepath.Rel(filepath.Clean(root), filepath.Clean(candidate))
	if err != nil {
		return false
	}
	return relative == "." || (relative != ".." && !strings.HasPrefix(relative, ".."+string(filepath.Separator)))
}

func resolvedPathWithin(root, candidate string) bool {
	resolvedRoot, rootErr := filepath.EvalSymlinks(root)
	resolvedCandidate, candidateErr := filepath.EvalSymlinks(candidate)
	if rootErr != nil || candidateErr != nil {
		return false
	}
	return pathWithin(filepath.Clean(resolvedRoot), filepath.Clean(resolvedCandidate))
}

func safeFileWithinRoot(root, filePath string) bool {
	return pathWithin(root, filePath) && resolvedPathWithin(root, filePath)
}

func stableTSID(kind string, values ...string) string {
	payload := kind + "\x00" + strings.Join(values, "\x00")
	sum := sha256.Sum256([]byte(payload))
	return "ts:" + kind + ":" + hex.EncodeToString(sum[:8])
}

func moduleIDForPath(relative string) string {
	value := filepath.ToSlash(filepath.Clean(relative))
	value = strings.TrimSuffix(value, filepath.Ext(value))
	return "ts:module:" + value
}

func moduleHierarchy(relative string) []string {
	value := filepath.ToSlash(filepath.Clean(relative))
	value = strings.TrimSuffix(value, filepath.Ext(value))
	if value == "." || value == "" {
		return []string{}
	}
	parts := strings.Split(value, "/")
	result := make([]string, 0, len(parts))
	for _, part := range parts {
		if part != "" && part != "." {
			result = append(result, part)
		}
	}
	return result
}

func moduleDisplayName(relative string) string {
	hierarchy := moduleHierarchy(relative)
	if len(hierarchy) == 0 {
		return ""
	}
	return hierarchy[len(hierarchy)-1]
}

func normalizedRelative(value string) string {
	value = filepath.ToSlash(filepath.Clean(strings.TrimSpace(value)))
	if value == "." {
		return ""
	}
	return strings.Trim(value, "/")
}

func defaultExcludedDirectory(relative string) bool {
	clean := normalizedRelative(relative)
	if clean == "" {
		return false
	}
	for _, segment := range strings.Split(clean, "/") {
		switch strings.ToLower(segment) {
		case ".git", ".hg", ".svn", ".cache", "cache", "coverage", "build", "dist", "out", "generated", "target", "tmp", "vendor", "external", "node_modules", "bower_components", "jspm_packages":
			return true
		}
	}
	return false
}

func isTestPath(relative, name string) bool {
	lowerPath := strings.ToLower(filepath.ToSlash(relative))
	for _, segment := range strings.Split(lowerPath, "/") {
		if segment == "test" || segment == "tests" || segment == "testing" || segment == "__tests__" {
			return true
		}
	}
	lowerName := strings.ToLower(name)
	base := lowerName
	for _, extension := range []string{".tsx", ".jsx", ".ts", ".js"} {
		base = strings.TrimSuffix(base, extension)
	}
	return strings.HasSuffix(base, ".test") || strings.HasSuffix(base, ".spec") ||
		strings.HasPrefix(base, "test_") || strings.HasPrefix(base, "test-") ||
		strings.HasSuffix(base, "_test") || strings.HasSuffix(base, "-test")
}

func excludedTSFile(relative, name string, project Project, includeTests bool) bool {
	if isTestPath(relative, name) && !includeTests {
		return true
	}
	if defaultExcludedDirectory(filepath.Dir(relative)) {
		return true
	}
	if project.CompilerOptions.OutDir != "" && pathWithin(project.CompilerOptions.OutDir, filepath.Join(project.Root, filepath.FromSlash(relative))) {
		return true
	}
	return excludedByPatterns(project.Root, relative, project.Exclude)
}

func generatedTSSource(content string) bool {
	lines := strings.Split(strings.ReplaceAll(content, "\r\n", "\n"), "\n")
	if len(lines) > 12 {
		lines = lines[:12]
	}
	for _, line := range lines {
		lower := strings.ToLower(strings.TrimSpace(line))
		if strings.Contains(lower, "code generated") && strings.Contains(lower, "do not edit") {
			return true
		}
		if strings.Contains(lower, "@generated") || strings.Contains(lower, "@autogenerated") {
			return true
		}
	}
	return false
}

func excludedByPatterns(root, relative string, patterns []SourcePattern) bool {
	absolute := filepath.Join(root, filepath.FromSlash(relative))
	for _, pattern := range patterns {
		if patternMatchesPath(pattern, absolute) {
			return true
		}
	}
	return false
}

func includedByPatterns(root, relative string, patterns []SourcePattern) bool {
	absolute := filepath.Join(root, filepath.FromSlash(relative))
	for _, pattern := range patterns {
		if patternMatchesPath(pattern, absolute) {
			return true
		}
	}
	return false
}

func patternMatchesPath(pattern SourcePattern, candidate string) bool {
	base := filepath.Clean(pattern.BaseDir)
	relative, err := filepath.Rel(base, filepath.Clean(candidate))
	if err != nil || relative == ".." || strings.HasPrefix(relative, ".."+string(filepath.Separator)) {
		value := normalizePatternForPath(pattern.Value)
		if relative == ".." || strings.HasPrefix(relative, ".."+string(filepath.Separator)) {
			if value != ".." && !strings.HasPrefix(value, "../") {
				return false
			}
		} else {
			return false
		}
	}
	relative = filepath.ToSlash(relative)
	value := normalizePatternForPath(pattern.Value)
	if runtime.GOOS == "windows" {
		relative = strings.ToLower(relative)
		value = strings.ToLower(value)
	}
	if value == "" || value == "." {
		return true
	}
	if globPathMatch(value, relative) {
		return true
	}
	// TypeScript treats a directory include/exclude as recursive even when
	// no wildcard was written.
	if !hasGlobMeta(value) && (relative == strings.TrimSuffix(value, "/") || strings.HasPrefix(relative, strings.TrimSuffix(value, "/")+"/")) {
		return true
	}
	return false
}

func globPathMatch(pattern, value string) bool {
	pattern = strings.Trim(filepath.ToSlash(pattern), "/")
	value = strings.Trim(filepath.ToSlash(value), "/")
	if pattern == value {
		return true
	}
	patternParts := splitPathPattern(pattern)
	valueParts := splitPathPattern(value)
	var match func(int, int) bool
	match = func(patternIndex, valueIndex int) bool {
		if patternIndex == len(patternParts) {
			return valueIndex == len(valueParts)
		}
		if patternParts[patternIndex] == "**" {
			if match(patternIndex+1, valueIndex) {
				return true
			}
			return valueIndex < len(valueParts) && match(patternIndex, valueIndex+1)
		}
		if valueIndex >= len(valueParts) {
			return false
		}
		segmentMatch, err := path.Match(patternParts[patternIndex], valueParts[valueIndex])
		return err == nil && segmentMatch && match(patternIndex+1, valueIndex+1)
	}
	return match(0, 0)
}

func splitPathPattern(value string) []string {
	if value == "" {
		return nil
	}
	parts := strings.Split(value, "/")
	result := make([]string, 0, len(parts))
	for _, part := range parts {
		if part != "" && part != "." {
			result = append(result, part)
		}
	}
	return result
}

func hasGlobMeta(value string) bool {
	return strings.ContainsAny(value, "*?[")
}

func unreadableTSDiagnostic(root, filePath string, err error) analysis.Diagnostic {
	path := relativeProjectPath(root, filePath)
	if path == "." {
		path = ""
	}
	return analysis.Diagnostic{
		Code:        "typescript_unreadable_file",
		Severity:    "error",
		Message:     fmt.Sprintf("TypeScript source path could not be read: %v", err),
		Path:        path,
		Recoverable: true,
	}
}

func sortTSDiagnostics(values []analysis.Diagnostic) {
	sort.Slice(values, func(i, j int) bool {
		left, _ := json.Marshal(values[i])
		right, _ := json.Marshal(values[j])
		return string(left) < string(right)
	})
}

func sortStringSet(values []string) []string {
	result := append([]string{}, values...)
	sort.Strings(result)
	write := 0
	for _, value := range result {
		if write == 0 || result[write-1] != value {
			result[write] = value
			write++
		}
	}
	return result[:write]
}

func appendUniqueString(values []string, value string) []string {
	for _, current := range values {
		if current == value {
			return values
		}
	}
	return append(values, value)
}
